language: python
os: linux
dist: bionic

jobs:
  - name: "Regular"

    python:
      - 3.7

    services: 
      - postgres

    install:
      - pip install -r requirements.txt

    before_script:
      - psql -c 'create database swe_app;' -U postgres
      - python manage.py migrate
      - python manage.py collectstatic --noinput

    script:
      - black --check .
      - flake8 .
      - coverage run --source=polls manage.py test

    after_script:
      - coveralls
  
  - name: "Containerized"

    env:
      - DOCKER_COMPOSE_VERSION=1.28.2
      - DOCKER_REPO='jackxujh/swe-app'

    before_install:
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      - RETRIEVED_TAG=$(docker manifest inspect $DOCKER_REPO:$TRAVIS_BRANCH > /dev/null && echo $TRAVIS_BRANCH || echo 'latest')
      - docker pull $DOCKER_REPO:$RETRIEVED_TAG

    script:
      - docker-compose build
      - docker-compose up migration
      - docker-compose run test
    
    after_script:
      - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - docker build -t $DOCKER_REPO:$TRAVIS_BRANCH .
      - docker push $DOCKER_REPO:$TRAVIS_BRANCH
