version: "3.9"
   
services:

  # setups with postgres database in a container

  db:
    image: postgres
    env_file: sample.env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: sample.env
    ports: 
      - "8000:8000"
    depends_on: 
      - db

  migration:
    build: .
    command: python manage.py migrate
    env_file: sample.env
    depends_on: 
      - db

  test:
    build: .
    command: python manage.py test
    env_file: sample.env
    depends_on: 
      - db
  
  createadmin:
    build: .
    command: sh -c "/code/scripts/create_admin.sh"
    env_file: sample.env
    depends_on: 
      - db
