version: "3.9"
   
services:

  # setups with postgres database in a container

  db:
    image: postgres
    env_file: sample.env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: sample.env
    ports: 
      - "8000:8000"
    depends_on: 
      - db

  migration:
    build: .
    command: python manage.py migrate
    env_file: sample.env
    depends_on: 
      - db

  test:
    build: .
    command: python manage.py test
    env_file: sample.env
    depends_on: 
      - db


  # setups with external postgres database

  web_external_db:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    environment: 
      - DB=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER #=jack
      - DB_PASSWORD #=
      
  migration_external_db:
    build: .
    command: python manage.py test
    environment: 
      - DB=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER #=jack
      - DB_PASSWORD #=

  test_external_db:
    build: .
    command: python manage.py test
    environment: 
      - DB=postgres
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER #=jack
      - DB_PASSWORD #=